In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
df_raw_stats = pd.read_csv("raw_stats.csv")

df_raw_stats = df_raw_stats.drop("Unnamed: 0", axis=1)
df_raw_stats = df_raw_stats.drop("Year", axis=1)
df_raw_stats

,Pos,G,MP,FG,FGA,3P,3PA,2P,2PA,FT,FTA,TRB,AST,STL,BLK,TOV,PF,PTS
0,C,76.0,2677.0,753.0,1301.0,0.0,3.0,753.0,1298.0,312.0,442.0,659.0,225.0,63.0,207.0,230.0,224.0,1818.0
1,C,79.0,2393.0,507.0,1027.0,0.0,1.0,507.0,1026.0,182.0,233.0,586.0,356.0,114.0,78.0,196.0,269.0,1196.0
2,SF,51.0,1468.0,381.0,820.0,25.0,71.0,356.0,749.0,168.0,247.0,249.0,164.0,37.0,22.0,135.0,152.0,955.0
3,SG,53.0,564.0,79.0,221.0,5.0,17.0,74.0,204.0,56.0,65.0,56.0,87.0,37.0,3.0,53.0,86.0,219.0
4,PG,68.0,2167.0,308.0,652.0,6.0,16.0,302.0,636.0,236.0,316.0,116.0,541.0,52.0,3.0,178.0,131.0,858.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16629,PF,62.0,1725.0,253.0,443.0,0.0,1.0,253.0,442.0,133.0,196.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
16630,C,51.0,525.0,78.0,158.0,0.0,1.0,78.0,157.0,22.0,39.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
16631,C,19.0,108.0,10.0,31.0,0.0,0.0,10.0,31.0,3.0,5.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
16632,SF,44.0,843.0,88.0,221.0,33.0,99.0,55.0,122.0,31.0,40.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
16633,C,38.0,609.0,126.0,238.0,0.0,3.0,126.0,235.0,32.0,49.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [3]:
target = df_raw_stats["Pos"]
target_names = ["C", "SF","SG","PF","PG"]

In [4]:
data = df_raw_stats.drop("Pos", axis=1)
feature_names = data.columns
data.head()

,G,MP,FG,FGA,3P,3PA,2P,2PA,FT,FTA,TRB,AST,STL,BLK,TOV,PF,PTS
0,76.0,2677.0,753.0,1301.0,0.0,3.0,753.0,1298.0,312.0,442.0,659.0,225.0,63.0,207.0,230.0,224.0,1818.0
1,79.0,2393.0,507.0,1027.0,0.0,1.0,507.0,1026.0,182.0,233.0,586.0,356.0,114.0,78.0,196.0,269.0,1196.0
2,51.0,1468.0,381.0,820.0,25.0,71.0,356.0,749.0,168.0,247.0,249.0,164.0,37.0,22.0,135.0,152.0,955.0
3,53.0,564.0,79.0,221.0,5.0,17.0,74.0,204.0,56.0,65.0,56.0,87.0,37.0,3.0,53.0,86.0,219.0
4,68.0,2167.0,308.0,652.0,6.0,16.0,302.0,636.0,236.0,316.0,116.0,541.0,52.0,3.0,178.0,131.0,858.0

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [6]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.5215195960567444

In [8]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.6314017792738639

In [9]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.1302260235983301, 'AST'),
 (0.11562717305451672, 'TRB'),
 (0.08864060016518459, 'BLK'),
 (0.07844155700726255, '3PA'),
 (0.060117582985443244, 'STL'),
 (0.057474905966307596, 'MP'),
 (0.0533979466535306, 'PF'),
 (0.050911391292445596, '3P'),
 (0.04940864126434792, 'TOV'),
 (0.0440686020716659, 'FGA'),
 (0.04240156919828298, 'PTS'),
 (0.04042707559475536, 'G'),
 (0.04001531153733886, '2PA'),
 (0.03919958958875176, 'FTA'),
 (0.037058049810684744, '2P'),
 (0.03639882518357001, 'FT'),
 (0.03618515502758129, 'FG')]